apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gitops-app
  namespace: ouchi-cicd-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-gitops-app
  template:
    metadata:
      labels:
        app: my-gitops-app
    spec:
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged:alpine
          ports:
            - containerPort: 8080
