apiVersion: v1
kind: Service
metadata:
  name: my-gitops-service
spec:
  selector:
    app: my-gitops-app
  ports:
    - port: 8080         # ① Service自身の受付ポート
      targetPort: 8080   # ② Pod（Nginx）へ渡すポート